### ISSUE TITLE
Create new node error

### ISSUE THREAD

**Issue by timmywiff** [nathanwoulfe/Plumber-2#4]
Hi, I'm getting an error when creating a new node. I have created Users, a Document Type, an Approval Group and I'm using the Trial features.

Umbraco 8.2.0

![image](https://user-images.githubusercontent.com/14854835/66908922-cd36ce80-f003-11e9-8590-970108806b81.png)

Stacktrace:
`at System.Data.SqlServerCe.SqlCeDataReader.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeDataReader.IsEndOfRowset(Int32 hr)
   at System.Data.SqlServerCe.SqlCeDataReader.Move(DIRECTION direction)
   at System.Data.SqlServerCe.SqlCeDataReader.Read()
   at NPoco.Database.<Read>d__156`1.MoveNext()
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at NPoco.Database.Fetch[T](String sql, Object[] args)
   at Plumber.Core.Repositories.Implement.Database.Fetch[T](String query, Object[] args)
   at Plumber.Core.Repositories.Implement.PermissionsRepository.AllPermissionsForNode(String[] path, Int32 contentTypeId)
   at Plumber.Core.Services.Implement.ConfigService.GetAllForNode(Int32 type, String path, String variant)
   at Plumber.Web.Api.ConfigController.GetNodeConfig(Int32 id, Int32 type, String path, String variant)`

**Comment by nathanwoulfe** [comment]
Hi @timmywiff, pretty sure I've resolved that in the current build, just need to publish to GitHub. Will get that up asap, provided I have actually fixed it...

**Comment by timmywiff** [comment]
Hi @nathanwoulfe, that's great news. I'm very keen to explore what this plugin can do and hopefully use it on a new project. I'll try and provide any useful feedback/issues.

**Comment by jenluong-deepend** [comment]
Hi there!
Has the latest build been published to GitHub? 
Currently have a fresh install of Umbraco: 8.3.0 and Plumber: 1.0.0-beta-000212 and getting this error!

**Comment by nathanwoulfe** [comment]
Hi @jenluong-deepend I've released a v1, it's on nuget now as plumber.workflow. Latest is v1.0.4
