### ISSUE TITLE
Sqlexception on installing plumber-2

### ISSUE THREAD

**Issue by SRandomName** [nathanwoulfe/Plumber-2#48]
**Describe the bug**
`Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Data.SqlClient.SqlException: Invalid column name 'AllowAttachments'.
Invalid column name 'RequireUnpublish'.
  at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
  at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
  at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
  at System.Data.SqlClient.SqlDataReader.get_MetaData()
  at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
  at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
  at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
  at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
  at System.Data.SqlClient.SqlCommand.ExecuteScalar()
  at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 346
  at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteScalar>b__32_0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 214
  at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
  at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
  at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
  at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteScalar() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 214
  at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
  at NPoco.DatabaseTypes.SqlServerDatabaseType.ExecuteInsert[T](Database db, DbCommand cmd, String primaryKeyName, Boolean useOutputClause, T poco, Object[] args)
  at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
  at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)
  at NPoco.Database.Insert[T](T poco)
  at Plumber.Core.Repositories.Implement.Database.Insert[T](Object model) in D:\a\1\s\Plumber.Core\Repositories\Implement\Database.cs:line 134
  at Plumber.Core.Repositories.Implement.BaseWorkflowRepository`1.Insert(TEntity entity) in D:\a\1\s\Plumber.Core\Repositories\Implement\WorkflowRepository.cs:line 31
  at Plumber.Web.Migrations.Plumber8_OneZeroZero.Migrate() in D:\a\1\s\Plumber.Web\Migrations\Plumber8_OneZeroZero.cs:line 27
  at Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() in D:\a\1\s\src\Umbraco.Core\Migrations\MigrationBase.cs:line 73
  at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) in D:\a\1\s\src\Umbraco.Core\Migrations\MigrationPlan.cs:line 313
  at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) in D:\a\1\s\src\Umbraco.Core\Migrations\Upgrade\Upgrader.cs:line 67
  at Plumber.Web.Migrations.WorkflowInstallMigration.Execute() in D:\a\1\s\Plumber.Web\Migrations\WorkflowInstallMigration.cs:line 39
  at Plumber.Web.WebComponent.Initialize() in D:\a\1\s\Plumber.Web\Components\WebComponent.cs:line 57
  at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 188`

**To Reproduce**
Fresh install of plumber-2

**Screenshots**

**Plumber version**
Which version of Plumber does the bug occur in? - Plumber 2

Any idea how to fix this problem ? Thanks !

**Comment by nathanwoulfe** [comment]
Hi @SRandomName, thanks for raising this - will be happening on all new installs of the latest version. Issue is caused by attempting to populate the settings table with a default entry as part of a migration. 

Issue is this:
- migration OneZeroZero creates the settings table, using SettingsSchema to define the table
- migration then adds a default entry to the settings table, using WorkflowSettingsPoco to populate the table
- schema does not change - it is the original value for the settings table
- poco does change - it has new values that don't exist in the schema
- can we see why this is a problem? 😄 
- migration attempts to add data via the poco into a table built using a schema which is missing columns, hence the error.

To fix it, I've moved the insert for the default settings outside of the migration, so that it happens after the final migration step, so will always be inserting the poco against the latest version of the settings table.

Building 1.4.2 now, should be on NuGet in 15 minutes or so.

**Comment by SRandomName** [comment]
Hey @nathanwoulfe, Thank you for your quick reply and fix !

**Comment by nathanwoulfe** [comment]
No worries at all, glad it wasn't anything major to fix.

**Comment by gurumurthyjv** [comment]
HI @nathanwoulfe ,

We also, have an similar issue with plumber 1.6.28 on Umbraco 8.14.

We have installed it through nuget in DEV environment, and we have deployed the code changes to our UAT (both DEV and UAT are 2 different environments with different DB's) and we are getting boot failed Umbraco exceptions. Below are some of the logs attached. This exception is from plumber migration as per logs.

Could you help us on how can we resolve this issue.

`D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:line 67\r\n   at Plumber.Web.Migrations.WorkflowInstallMigration.Execute() in D:\\a\\1\\s\\Plumber.Web\\Migrations\\WorkflowInstallMigration.cs:line 40\r\n   at Plumber.Web.WebComponent.Initialize() in D:\\a\\1\\s\\Plumber.Web\\Components\\WebComponent.cs:line 64\r\n   at `

`{"@t":"2021-12-30T16:30:02.9029982Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Data.SqlClient.SqlException: CREATE TABLE permission denied in database 'umbecsmyarrowuat-sqldb'.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at `

Thanks,
Gurumurthy J V
