### ISSUE TITLE
System.Exception: SQL Server 2012 Paging via OFFSET requires an ORDER BY statement.

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#59]
Hi Nathan,

On a live site, since upgrading to the latest version the following error is being logged:

```
System.Exception: SQL Server 2012 Paging via OFFSET requires an ORDER BY statement.
   at NPoco.DatabaseTypes.SqlServer2012DatabaseType.BuildPageQuery(Int64 skip, Int64 take, SQLParts parts, Object[]& args)
   at NPoco.Database.BuildPageQueries[T](Int64 skip, Int64 take, String sql, Object[]& args, String& sqlCount, String& sqlPage)
   at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at Plumber.Core.Repositories.Implement.Database.Page[T](Int32 page, Int32 count, String query, Object[] args) in D:\a\1\s\Plumber.Core\Repositories\Implement\Database.cs:line 55
   at Plumber.Core.Repositories.Implement.BaseWorkflowRepository`1.Page(Int32 page, Int32 count, String query, Object[] args) in D:\a\1\s\Plumber.Core\Repositories\Implement\WorkflowRepository.cs:line 94
   at Plumber.Core.Services.Implement.InstancesService.GetFilteredPagedInstancesForDateRange(DateTime oldest, Nullable`1 count, Nullable`1 page, String filter) in D:\a\1\s\Plumber.Core\Services\Implement\InstancesService.cs:line 200
   at Plumber.Web.Api.InstancesController.GetFilteredPagedInstancesForDateRange(Int32 days, String filter, Nullable`1 count, Nullable`1 page) in D:\a\1\s\Plumber.Web\Api\InstancesController.cs:line 104
```

**Comment by nathanwoulfe** [comment]
Hi @NikRimington I would have sworn I'd fixed that... Will fix it properly this time...

**Comment by nathanwoulfe** [comment]
Ok, so this is a bit strange - the SQL executed for `GetFilteredPagedInstancesForDateRange` looks like this:

```
SELECT * FROM WorkflowInstance                           
WHERE (WorkflowInstance.CompletedDate IS NULL OR WorkflowInstance.CompletedDate >= CONVERT(DATETIME, @0))
AND (@1 = -1 OR WorkflowInstance.Status = @1)
ORDER BY WorkflowInstance.CompletedDate DESC
```

Most certainly has an order-by clause. The order-by was added in the last release, so I'm not going crazy thinking I'd worked on it... Is it possible that the DLLs are stale or didn't update when the package was upgraded? Strange though that you'd start seeing the error after an upgrade, given the order-by was missing previously...

**Comment by nathanwoulfe** [comment]
@NikRimington realised I didn't tag you in my previous response. Could you double check the dll versions etc...

**Comment by NikRimington** [comment]
Hey @nathanwoulfe I think it might be fixed in the latest release. I noticed that after a clean deployment it seems to have disappeared. Can't see any more entries for it in the logs since a deployment happened (after raising this ticket).

**Comment by nathanwoulfe** [comment]
@NikRimington good to hear it's resolved, let me know though if it returns.
