### ISSUE TITLE
Exception when loading content items

### ISSUE THREAD

**Issue by callumbwhyte** [nathanwoulfe/Plumber-2#66]
Since upgrading to Umbraco 8.10.1 and Plumber 1.5.0 we've been getting errors when loading any content item.

The `/umbraco/backoffice/Plumber/Scaffold` endpoint throws the following error:

```
System.ArgumentNullException: Value cannot be null. Parameter name: value
at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.Set(String key, Object value, CacheItemPolicy policy, String regionName)
   at Plumber.Core.Services.Implement.SettingsService.SetCache(String key, Object thing) in D:\a\1\s\Plumber.Core\Services\Implement\SettingsService.cs:line 262
   at Plumber.Core.Services.Implement.SettingsService.GetSettings() in D:\a\1\s\Plumber.Core\Services\Implement\SettingsService.cs:line 47
   at Plumber.Web.Api.ScaffoldController.Get(Int32 id, Int32 contentTypeId, String path, String variant) in D:\a\1\s\Plumber.Web\Api\ScaffoldController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

As a result of the error the "Save & Publish" buttons are initially hidden when loading any content item - only the "Save" button is visible. After saving the content item the "Save & Publish" buttons re-appear.

I haven't tested this on any other versions of Umbraco, but as the error is in Plumber I assume that won't matter.

**Comment by nathanwoulfe** [comment]
That's not good. Could you check the WorkflowSettings table - it should have a single row only, I was seeing some cases where a second was being added, so dealt with that, but now it looks like there's no value found to bang into cache...

**Comment by nathanwoulfe** [comment]
@callumbwhyte I've installed 1.5 into a freshly updated 8.10.1 site, no exception... It's somehow related to the data in the WorkflowSettings table, just need some insight into what is in there.

**Comment by callumbwhyte** [comment]
@nathanwoulfe Confirmed that the `WorkflowSettings` table is empty. This isn't a site that's been upgraded.

**Comment by nathanwoulfe** [comment]
@callumbwhyte that's not good. To clarify - is this a new install of Plumber, or an existing site where both Umbraco and Plumber have been upgraded? Bit concerning that the settings would be gone (assuming it's not a new install)

**Comment by callumbwhyte** [comment]
Hey @nathanwoulfe, this is an upgraded site - Plumber was installed ~December 2019 back on Umbraco 8.3/8.4.

**Comment by nathanwoulfe** [comment]
Really strange - I ran the upgrade on a local site from 8.6 to 8.10.1, then updated Plumber to 1.5.0, no issues. Somewhere in the upgrade your settings table has dropped its content..

**Comment by nathanwoulfe** [comment]
Otherwise, going to the workflow section and saving the settings should insert a new row. Failing that, restarting the site should insert a new row if none exist.

**Comment by nathanwoulfe** [comment]
And building a patch now - I haven't solved where the settings went, but the patch will insert a default settings object if none exist on startup. That should have been the case previously, but I was updating rather than inserting, which ain't gonna work if there's nothing to update.

Patch will be Plumber.Workflow.1.5.1-beta-000508

**Comment by Elethiomeluk** [comment]
I had similar issues when I updated a local site to 8.10.1 and Plumber 1.5.0 (from 8.8.2 and 1.4.3) - I didn't have time to look into it (in the middle of a big redesign project) but downgrading to Plumber 1.4.3 seemed to fix it.

Just tried upgrading back to 1.5.0; before the upgrade, WorkflowSettings had a single row; after upgrading, there is still a row in there, but the following error occurs when trying to load any content page:

```
An error occurred
Value cannot be null. Parameter name: value

Exception Details
System.ArgumentNullException: Value cannot be null. Parameter name: value

at System.Runtime.Caching.MemoryCacheEntry..ctor(String key, Object value, DateTimeOffset absExp, TimeSpan slidingExp, CacheItemPriority priority, Collection`1 dependencies, CacheEntryRemovedCallback removedCallback, MemoryCache cache)
   at System.Runtime.Caching.MemoryCache.Set(String key, Object value, CacheItemPolicy policy, String regionName)
   at Plumber.Core.Services.Implement.SettingsService.SetCache(String key, Object thing) in D:\a\1\s\Plumber.Core\Services\Implement\SettingsService.cs:line 260
   at Plumber.Core.Services.Implement.SettingsService.GetSettings() in D:\a\1\s\Plumber.Core\Services\Implement\SettingsService.cs:line 45
   at Plumber.Web.Api.ScaffoldController.Get(Int32 id, Int32 contentTypeId, String path, String variant) in D:\a\1\s\Plumber.Web\Api\ScaffoldController.cs:line 38
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by nathanwoulfe** [comment]
@Elethiomeluk definitely the same error - try updating to the latest nightly (1.5.1), and see if that helps...

Is there anything else about your setup that might be contributing?

**Comment by Chris-N1** [comment]
Oops, didn't realise I was logged in on my other account, 'tis I! (Trying out Edge as a default browser and must have logged into the wrong account).

Hmm - on the local installation there are no approval groups at the moment; I could add one back. Apart from that I don't think there's anything odd - quite a few other packages installed but I wouldn't expect any of them to interfere with Plumber.

I'll try the latest nightly, ta.

**Comment by nathanwoulfe** [comment]
It's got me puzzled for sure - code gets settings from the database, if none exist it creates a new object, then punts it into memory for later. Can't see where that would be coming undo...

**Comment by nathanwoulfe** [comment]
Actually I might also revert some changes from 1.5.0 which were added to manage sites updating from umb7 to 8, add a manual step in the docs, and get 1.5.2 back to the last known stable state. 

Unless of course 1.5.1 fixes the issue 😁

**Comment by callumbwhyte** [comment]
@nathanwoulfe I've updated to v1.5.1-beta and confirmed that it fixes the issue.

The "Save & Publish" buttons flicker for a while on load, but at least it's functional.

![Buttons](https://user-images.githubusercontent.com/16511093/105628293-fca5cf00-5e33-11eb-81ba-775e32a04194.gif)

**Comment by nathanwoulfe** [comment]
@callumbwhyte glad to hear it - still not sure why this would have happened, but such is life. 

Will see if I can improve the button display, should be able to hide the buttons until the final state is determined

**Comment by nathanwoulfe** [comment]
@callumbwhyte latest nightly has no flickering buttons.
