### ISSUE TITLE
Request publish

### ISSUE THREAD

**Issue by jenluong-deepend** [nathanwoulfe/Plumber-2#8]
**Versions**
Fresh install of Umbraco: 8.3.0 & Plumber: 1.0.4

**Issue**
I enter a comment into "Describe the changes" and then press "Request Publish" and then I get this error

```
at Plumber.Core.Notifications.Emailer.Send(WorkflowInstancePoco instance, EmailType emailType, String errorDetail)
   at Plumber.Core.Services.Implement.NotificationsService.SendEmailNotifications(WorkflowInstancePoco instance, EmailType emailType, String errorDetail)
   at Plumber.Core.Processes.WorkflowProcess.ApproveOrContinue(WorkflowTaskPoco taskInstance, Nullable`1 userId, String comment)
   at Plumber.Core.Processes.WorkflowProcess.InitiateWorkflow(Int32 nodeId, Int32 contentTypeId, Int32 authorUserId, String authorComment, String variant)
   at Plumber.Web.Api.ActionsController.InitiateWorkflow(InitiateWorkflowModel model)
```

I thought maybe the SMTP details were incorrect so I did a test "forgot password" email for a CMS user and received the email correctly.

Looks like it partially works because I can see the count for "pending" increment.

![image](https://user-images.githubusercontent.com/40009643/68913985-1b7cf000-07b1-11ea-9731-08a3dbd060f9.png)

 I also checked the database and it looks like it the task is being added to the `[WorkflowTaskInstance]` table.

**Comment by nathanwoulfe** [comment]
Something dead in the emailer. I'll look into it

**Comment by nathanwoulfe** [comment]
@jenluong-deepend this should be resolved in 1.0.5 - update via nuget, let me know if it's ok. It was a pretty obvious bug, so I'm confident it will be ok (famous last words).

**Comment by nathanwoulfe** [comment]
@jenluong-deepend skip 1.0.5, I released 1.0.6 last weekend with a few more fixes and things
